### ISSUE TITLE
Problems with angular-animate and Phonegap

### ISSUE THREAD

**Issue by NEOLPAR** [marcoslin/angularAMD#52]
I have a specific problem with angular-animate when I run it in Phonegap.
I have done the AngularJS documentation process for do a simple animation.
https://code.angularjs.org/1.2.0-rc.3/docs/api/ngAnimate

``` javascript
"config-require.js"

require.config({

    baseUrl: "./js",
    paths: {
            'angular'         : '../libs/angular',
            'angular-route'   : '../libs/angular-route',
            'angular-animate' : '../libs/angular-animate'
    },
    shim: {
            'angularAMD'      : ['angular'],
            'angular-route'   : ['angular'],
            'angular-animate' : ['angular']
    },
    deps: ['app']
});
```

``` javascript
"app.js"

define(['angularAMD', 'angular-route', 'angular-animate'], function (angularAMD) {
    var app = angular.module("com.grupocampus.arbitros-fvfbff", ['ngRoute', 'ngAnimate']);
```

``` css
.reveal-animation.ng-enter {
  -webkit-animation: enter_sequence 1s linear; /* Safari/Chrome */
  -moz-animation: enter_sequence 1s linear; /* Firefox */
  -o-animation: enter_sequence 1s linear; /* Opera */
  animation: enter_sequence 1s linear; /* IE10+ and Future Browsers */
}
@-webkit-keyframes enter_sequence {
  from { opacity:0; }
  to { opacity:1; }
}
@-moz-keyframes enter_sequence {
  from { opacity:0; }
  to { opacity:1; }
}
@-o-keyframes enter_sequence {
  from { opacity:0; }
  to { opacity:1; }
}
@keyframes enter_sequence {
  from { opacity:0; }
  to { opacity:1; }
}
```

``` html
<div class="reveal-animation" ng-view></div>
```

I test it in Firefox, Chrome, Chromium and Canary and it is running perfectly, without errors. But when I build in Phonegap and run it, LogCat gives me this error:

```
TypeError: undefined is not a function
    at file:///android_asset/www/libs/angular.js:11328:16
    at file:///android_asset/www/libs/angular-animate.js:267:14
    at afterReflow (file:///android_asset/www/libs/angular-animate.js:1097:33)
    at animate (file:///android_asset/www/libs/angular-animate.js:1471:9)
    at Object.fn (file:///android_asset/www/libs/angular-animate.js:1504:18)
    at file:///android_asset/www/libs/angular-animate.js:456:46
    at Array.forEach (native)
    at forEach (file:///android_asset/www/libs/angular.js:322:11)
    at run (file:///android_asset/www/libs/angular-animate.js:441:11)
    at Object.before (file:///android_asset/www/libs/angular-animate.js:474:13) at file:///android_asset/www/libs/angular.js:9509
```

Someone could help me? Someone have had this problem or similar?
